version: '3.8'
services:
  backend:
    build: ./api
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: "mysql://user:password@host:port/dbname"
      CORS_ORIGIN: "http://localhost:3000"
      JWT_SECRET: "your_jwt_secret"
      # Add other backend env vars as needed
    depends_on:
      - db
  frontend:
    build: ./client
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: "http://localhost:3001"
      # Add other frontend env vars as needed
    depends_on:
      - backend
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: blogdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data: