version: '3.8'

services:
  backend:
    build: 
      context: ./api
      dockerfile: Dockerfile.k8s
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      CORS_ORIGIN: ${CORS_ORIGIN:-https://blog.ingasti.com}
      PORT: 5000
      NODE_ENV: production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  frontend:
    build: 
      context: ./client
      dockerfile: Dockerfile.k8s
    ports:
      - "3000:80"
    environment:
      VITE_API_URL: ${VITE_API_URL:-https://bapi.ingasti.com}
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    restart: unless-stopped

networks:
  default:
    name: blog-network
