version: '3.8'
services:
  backend:
    build: ./api
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: ${DATABASE_URL} # Injected by Jenkins credentials
      CORS_ORIGIN: ${CORS_ORIGIN:-http://localhost:3000}
      JWT_SECRET: ${JWT_SECRET} # Injected by Jenkins credentials
      PORT: 5000
      NODE_ENV: production
      # Add other backend env vars as needed
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health", "||", "curl", "-f", "http://localhost:5000"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
  frontend:
    build: ./client
    ports:
      - "3000:80"  # nginx serves on port 80 inside container
    environment:
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://localhost:5000}
      # Add other frontend env vars as needed
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s