apiVersion: v1
kind: Secret
metadata:
  name: blog-secrets
  namespace: blog
type: Opaque
data:
  PGHOST: aW5nYXN0aS1wZy1pbmdhc3RpLmMuYWl2ZW5jbG91ZC5jb20=
  PGPORT: MjUzMDY=
  PGDATABASE: YmxvZw==
  PGUSER: YXZuYWRtaW4=
  PGPASSWORD: QVZOU19FZjlscUQzeUJvbGdnNndkRmZp
  PGSSLMODE: cmVxdWlyZQ==
  BLOG_API_KEY: ODExMjhiNzA5MTVmZTJkNjkwYTRlNTVlZWJlYjEzY2VkZjA2OTY1OWU4ZTUyNGMxMTk4NDI2ZDc2NjU0NjJiMA==
  BLOG_API_URL: aHR0cHM6Ly9iYXBpLmluZ2FzdGkuY29tL2FwaQ==
  BLOG_USER_ID: MQ==
  # Google OAuth credentials (base64 encoded)
  GOOGLE_CLIENT_ID: WU9VUl9HT09HTEVfQ0xJRU5UX0lE  # Replace with your actual Google Client ID (base64)
  GOOGLE_CLIENT_SECRET: WU9VUl9HT09HTEVfQ0xJRU5UX1NFQ1JFVA==  # Replace with your actual Google Client Secret (base64)
