apiVersionapiVersion: v1
kind: ServiceAccount
metadata:
  name: media-access-sa
  namespace: blog
  # Remove EKS annotation - we're using K3s OIDC, not EKS IRSA
  # annotations:
  #   eks.amazonaws.com/role-arn: arn:aws:iam::007041844937:role/BedtimeBlogMediaRole
---
# Token secret for the service account (required for K3s OIDC)
apiVersion: v1
kind: Secret
metadata:
  name: media-access-sa-token
  namespace: blog
  annotations:
    kubernetes.io/service-account.name: media-access-sa
type: kubernetes.io/service-account-tokend: ServiceAccount
metadata:
  name: media-access-sa
  namespace: blog
  labels:
    app: blog-backend
    component: media-access
automountServiceAccountToken: true
---
apiVersion: v1
kind: Secret
metadata:
  name: media-access-token
  namespace: blog
  annotations:
    kubernetes.io/service-account.name: media-access-sa
type: kubernetes.io/service-account-token