apiVersion: v1
kind: ServiceAccount
metadata:
  name: media-access-sa
  namespace: blog
  labels:
    app: blog-backend
    component: media-access
automountServiceAccountToken: true
---
apiVersion: v1
kind: Secret
metadata:
  name: media-access-sa-token
  namespace: blog
  annotations:
    kubernetes.io/service-account.name: media-access-sa
type: kubernetes.io/service-account-token
