#!/bin/bash

echo "🔑 GitHub Webhook + API Configuration Guide"
echo "==========================================="
echo ""

echo "📋 CREDENTIAL TYPES EXPLAINED:"
echo "------------------------------"
echo ""
echo "1. 🔐 GitHub API Token (for Jenkins ↔ GitHub API)"
echo "   • Used by Jenkins to communicate with GitHub API"
echo "   • Required for: repository access, webhook management, status updates"
echo "   • Format: ghp_xxxxxxxxxxxx or github_pat_xxxxxxxxxxxx"
echo "   • Permissions needed: repo, admin:repo_hook"
echo ""
echo "2. 🔑 Webhook Secret (for GitHub → Jenkins webhooks)"
echo "   • Used to verify webhook payloads with HMAC-SHA256"
echo "   • Prevents unauthorized webhook calls"
echo "   • Your secret: 5002b8584e6dc478cca3b4591760b4277870bab41aa6eb94fe95268e9a8a850e"
echo "   • Used in: GitHub webhook config AND Jenkins job config"
echo ""

echo "🛠️  STEP-BY-STEP FIX:"
echo "====================="
echo ""
echo "STEP 1: Create GitHub Personal Access Token"
echo "-------------------------------------------"
echo "1. Go to: https://github.com/settings/tokens"
echo "2. Click: 'Generate new token' → 'Generate new token (classic)'"
echo "3. Name: 'Jenkins API Access'"
echo "4. Permissions:"
echo "   ✅ repo (Full control of private repositories)"
echo "   ✅ admin:repo_hook (Admin access to repository hooks)"
echo "5. Generate token and COPY IT (starts with ghp_ or github_pat_)"
echo ""

echo "STEP 2: Add GitHub API Token to Jenkins"
echo "---------------------------------------"
echo "1. Jenkins → Manage Jenkins → Credentials → System → Global"
echo "2. Add Credentials:"
echo "   • Kind: Secret text"
echo "   • Secret: [Your GitHub token from Step 1]"
echo "   • ID: github-api-token"
echo "   • Description: GitHub API Token for Jenkins"
echo "3. Save"
echo ""

echo "STEP 3: Update Jenkins GitHub Server Config"
echo "-------------------------------------------"
echo "1. Jenkins → Manage Jenkins → Configure System → GitHub"
echo "2. Credentials: Select 'GitHub API Token for Jenkins'"
echo "3. Test connection - should show ✅ success"
echo "4. Save"
echo ""

echo "STEP 4: Verify Webhook Secret Configuration"
echo "-------------------------------------------"
echo "1. GitHub → Repo → Settings → Webhooks → Your webhook"
echo "2. Secret field should contain:"
echo "   5002b8584e6dc478cca3b4591760b4277870bab41aa6eb94fe95268e9a8a850e"
echo "3. Make sure webhook is Active ✅"
echo ""

echo "STEP 5: Test the Complete Setup"
echo "-------------------------------"
echo "1. Make a small change to your repo:"
echo "   echo '# Webhook test' >> README.md"
echo "   git add README.md"
echo "   git commit -m 'Test webhook configuration'"
echo "   git push origin k8s"
echo ""
echo "2. Check results:"
echo "   • GitHub webhook deliveries should show 200 OK"
echo "   • Jenkins job should automatically trigger"
echo "   • Build should complete successfully"
echo ""

echo "🔍 TROUBLESHOOTING:"
echo "==================="
echo ""
echo "If webhook still fails:"
echo "• Check Jenkins system logs: https://jenkins.ingasti.com/log/all"
echo "• Verify GitHub webhook deliveries: GitHub → Repo → Settings → Webhooks"
echo "• Ensure both credentials are properly configured"
echo ""
echo "If API connection fails:"
echo "• Verify GitHub token has correct permissions"
echo "• Check if token has expired"
echo "• Ensure Jenkins can reach api.github.com"
