#!/bin/bash

echo "🔍 Jenkins Webhook Configuration Helper"
echo "======================================"
echo ""

echo "📋 STEP 1: Check Your Jenkins Job Configuration"
echo "----------------------------------------------"
echo "1. Go to: https://jenkins.ingasti.com/job/bedtimeblog-k8s/configure"
echo "   (or whatever your job name is)"
echo ""
echo "2. Look for these sections and check the settings:"
echo ""
echo "   📂 Source Code Management:"
echo "   • Repository URL should be: https://github.com/jcgarcia/bedtimeblog.git"
echo "   • Credentials: Look for a dropdown to select webhook credentials"
echo "   • Branch Specifier: Should be */k8s or */*"
echo ""
echo "   ⚡ Build Triggers:"
echo "   • ✅ GitHub hook trigger for GITScm polling (should be checked)"
echo "   • Look for any secret/credential options in this section"
echo ""

echo "📋 STEP 2: Check Jenkins Global GitHub Configuration"
echo "--------------------------------------------------"
echo "1. Go to: https://jenkins.ingasti.com/manage/configure"
echo "2. Scroll down to find 'GitHub' section"
echo "3. Look for:"
echo "   • GitHub Servers configuration"
echo "   • Webhook secret settings"
echo "   • Add your webhook secret credential if needed"
echo ""

echo "📋 STEP 3: Check Jenkins Security Configuration"
echo "---------------------------------------------"
echo "1. Go to: https://jenkins.ingasti.com/manage/configureSecurity/"
echo "2. Look for:"
echo "   • CSRF Protection: Should have 'Enable proxy compatibility' ✅"
echo "   • Any webhook-related security settings"
echo ""

echo "📋 STEP 4: Verify Installed Plugins"
echo "----------------------------------"
echo "1. Go to: https://jenkins.ingasti.com/manage/pluginManager/installed"
echo "2. Search for these plugins (they should be installed):"
echo "   • GitHub plugin"
echo "   • GitHub Branch Source plugin"
echo "   • Git plugin"
echo "   • Webhooks plugin"
echo ""

echo "🔧 MOST LIKELY FIX:"
echo "=================="
echo ""
echo "The issue is probably that your Jenkins job needs to be configured"
echo "to use the webhook secret credential. Here's what to do:"
echo ""
echo "1. Jenkins Job → Configure → Source Code Management"
echo "2. Look for 'Additional Behaviours' or 'Advanced' button"
echo "3. Add 'GitHub Webhook Verification' behavior if available"
echo "4. Select your webhook secret credential"
echo ""
echo "OR:"
echo ""
echo "1. Manage Jenkins → Configure System → GitHub section"
echo "2. Add GitHub Server if not configured"
echo "3. Set API URL: https://api.github.com"
echo "4. Set webhook secret to your credential"
echo "5. Test connection"
echo ""

echo "🧪 Quick Test After Configuration:"
echo "================================="
echo "After making changes, test by pushing a commit to your k8s branch:"
echo ""
echo "git add ."
echo "git commit -m 'Test webhook trigger'"
echo "git push origin k8s"
echo ""
echo "Then check:"
echo "• GitHub webhook delivery logs"
echo "• Jenkins job build history"
echo "• Jenkins system logs if build doesn't trigger"
