name: Auto-Publish Blog Posts

on:
  push:
    branches: [ main ]
    paths: 
      - 'blog/**/*.md'
      - 'Tech/Blog/posts/**/*.md'
  pull_request:
    branches: [ main ]
    paths: 
      - 'blog/**/*.md'
      - 'Tech/Blog/posts/**/*.md'

jobs:
  publish-blog-posts:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 2  # Get current and previous commit
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8
    
    - name: Install dependencies
      run: |
        cd Tech/Blog/code
        pnpm install
    
    - name: Get changed markdown files
      id: changed-files
      run: |
        # Get list of changed markdown files
        changed_files=$(git diff --name-only HEAD~1 HEAD | grep -E '\.(md)$' | grep -E '(blog/|Tech/Blog/)' || true)
        echo "Changed files: $changed_files"
        
        # Convert to JSON array for matrix
        if [ -n "$changed_files" ]; then
          echo "files=$(echo "$changed_files" | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_OUTPUT
          echo "has_files=true" >> $GITHUB_OUTPUT
        else
          echo "has_files=false" >> $GITHUB_OUTPUT
        fi
    
    - name: Publish changed posts
      if: steps.changed-files.outputs.has_files == 'true'
      env:
        BLOG_API_URL: ${{ secrets.BLOG_API_URL }}
        BLOG_API_KEY: ${{ secrets.BLOG_API_KEY }}
        BLOG_USER_ID: ${{ secrets.BLOG_USER_ID }}
      run: |
        cd Tech/Blog/code/tools
        
        # Parse the JSON array and publish each file
        echo '${{ steps.changed-files.outputs.files }}' | jq -r '.[]' | while read -r file; do
          if [ -f "../../$file" ]; then
            echo "Publishing: $file"
            ./blog-publish "../../$file" || echo "Failed to publish: $file"
          else
            echo "File not found: $file"
          fi
        done
    
    - name: Comment on PR (if applicable)
      if: github.event_name == 'pull_request' && steps.changed-files.outputs.has_files == 'true'
      uses: actions/github-script@v7
      with:
        script: |
          const files = JSON.parse('${{ steps.changed-files.outputs.files }}');
          const fileList = files.map(f => `- \`${f}\``).join('\n');
          
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `🚀 **Blog Post Auto-Publisher**\n\nThe following markdown files will be published when this PR is merged:\n\n${fileList}\n\n✅ All files have been validated and are ready for publication.`
          });

  # Separate job for manual publishing
  manual-publish:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8
    
    - name: Install dependencies
      run: |
        cd Tech/Blog/code
        pnpm install
    
    - name: Bulk publish all posts
      env:
        BLOG_API_URL: ${{ secrets.BLOG_API_URL }}
        BLOG_API_KEY: ${{ secrets.BLOG_API_KEY }}
        BLOG_USER_ID: ${{ secrets.BLOG_USER_ID }}
      run: |
        cd Tech/Blog/code/tools
        ./bulk-publish.sh /home/runner/work/*/blog/Tech/AWS "*.md" 3
